#!/bin/sh

echo ""
echo "                 _            "
echo " _   _  __ _  __| |_ __ ___   "
echo "| | | |/ _\` |/ _\` | '_ \` _ \  "
echo "| |_| | (_| | (_| | | | | | | "
echo " \__, |\__,_|\__,_|_| |_| |_| "
echo " |___/                        "
echo "                  ...bootstrap"
echo ""
