format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$golang\
$helm\
$java\
$nodejs\
$python\
$nix_shell\
$memory_usage\
$aws\
$env_var\
$custom\
$line_break\
$status\
$character"""

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "❯❯[❯](green)"
error_symbol = "❯❯[❯](red)"

[aws]
disabled = true
